// <auto-generated />
using System;
using DominoPontaDeQuina.Repository.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DominoPontaDeQuina.Repository.Migrations
{
    [DbContext(typeof(DominoDbContext))]
    [Migration("20260813123517_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.15");

            modelBuilder.Entity("DominoPontaDeQuina.Domain.Entities.Jogador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeExibicao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("NomeExibicao");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("TEXT")
                        .HasColumnName("UsuarioId");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("IX_Jogadores_UsuarioId");

                    b.ToTable("Jogadores", (string)null);
                });

            modelBuilder.Entity("DominoPontaDeQuina.Domain.Entities.Jogo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FinalizadoEm")
                        .HasColumnType("TEXT")
                        .HasColumnName("FinalizadoEm");

                    b.Property<DateTime>("IniciadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("IniciadoEm")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("Status");

                    b.HasKey("Id");

                    b.HasIndex("IniciadoEm")
                        .HasDatabaseName("IX_Jogos_IniciadoEm");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Jogos_Status");

                    b.ToTable("Jogos", (string)null);
                });

            modelBuilder.Entity("DominoPontaDeQuina.Domain.Entities.ParticipacaoJogo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("JogadorId")
                        .HasColumnType("TEXT")
                        .HasColumnName("JogadorId");

                    b.Property<Guid>("JogoId")
                        .HasColumnType("TEXT")
                        .HasColumnName("JogoId");

                    b.Property<int>("Pontuacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("Pontuacao");

                    b.Property<int>("Posicao")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Posicao");

                    b.Property<bool>("Vencedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("Vencedor");

                    b.HasKey("Id");

                    b.HasIndex("JogadorId")
                        .HasDatabaseName("IX_ParticipacoesJogo_JogadorId");

                    b.HasIndex("JogoId")
                        .HasDatabaseName("IX_ParticipacoesJogo_JogoId");

                    b.HasIndex("JogoId", "JogadorId")
                        .IsUnique()
                        .HasDatabaseName("IX_ParticipacoesJogo_JogoId_JogadorId");

                    b.ToTable("ParticipacoesJogo", (string)null);
                });

            modelBuilder.Entity("DominoPontaDeQuina.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasColumnName("CriadoEm")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("Email");

                    b.Property<string>("HashSenha")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("HashSenha");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("Nome");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Usuarios_Email");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("DominoPontaDeQuina.Domain.Entities.Jogador", b =>
                {
                    b.HasOne("DominoPontaDeQuina.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Jogadores")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("DominoPontaDeQuina.Domain.Entities.ParticipacaoJogo", b =>
                {
                    b.HasOne("DominoPontaDeQuina.Domain.Entities.Jogador", "Jogador")
                        .WithMany("Participacoes")
                        .HasForeignKey("JogadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DominoPontaDeQuina.Domain.Entities.Jogo", "Jogo")
                        .WithMany("Participacoes")
                        .HasForeignKey("JogoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jogador");

                    b.Navigation("Jogo");
                });

            modelBuilder.Entity("DominoPontaDeQuina.Domain.Entities.Jogador", b =>
                {
                    b.Navigation("Participacoes");
                });

            modelBuilder.Entity("DominoPontaDeQuina.Domain.Entities.Jogo", b =>
                {
                    b.Navigation("Participacoes");
                });

            modelBuilder.Entity("DominoPontaDeQuina.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Jogadores");
                });
#pragma warning restore 612, 618
        }
    }
}
